version: '3'

services:
  # NGINX + FPM + PHP 8.2
  app:
    container_name: lara-app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "${APP_EXTERNAL_PORT}:80"
      - "${APP_EXTERNAL_PORT_SSL}:443"
    tty: true
    extra_hosts:
      - "test.local:127.0.0.1"
    hostname: test
    domainname: local
    networks:
      - lara-network
    depends_on:
      - redis
      - mysql

  # REDIS
  redis:
    container_name: lara-redis
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
    volumes:
      - ./docker/redis/data:/data
    networks:
      - lara-network

  # MYSQL
  mysql:
    image: mysql:8.0
    container_name: lara-mysql
    ports:
      - "${DB_EXTERNAL_PORT}:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - lara-network


networks:
  lara-network:
    driver: bridge

volumes:
  dbdata:
    driver: local